[[getting-started]]
= Getting Started

This section offers jumping off points for how to get started using Spring AI.

== Dependency Management

The Spring AI project provides artifacts in the Spring Milestone and Snapshot repositories.

You need to add references to the Spring Milestone and/or Snapshot repositories in your build file.

For Maven, add the following repository definitions as needed:

[source,xml]
----
  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
----

For Gradle, add the following repository definitions as needed:

[source,groovy]
----
repositories {
  mavenCentral()
  maven { url 'https://repo.spring.io/milestone' }
  maven { url 'https://repo.spring.io/snapshot' }
}
----



== Chat Models

* xref:api/clients/openai-chat.adoc[OpenAI]
* xref:api/clients/azure-openai-chat.adoc[Azure OpenAI]
* xref:api/clients/huggingface.adoc[HuggingFace]
* xref:api/clients/bedrock.adoc[Bedrock]
* xref:api/clients/ollama-chat.adoc[Ollama]

== Embedding Models

* xref:api/embeddings/openai-embeddings.adoc[OpenAI Embeddings]
* xref:api/embeddings/azure-openai-embeddings.adoc[Azure OpenAI Embeddings]
* xref:api/embeddings/ollama-embeddings.adoc[Ollama Embeddings]
* xref:api/embeddings/onnx.adoc[Transformers (ONNX) Embeddings]
* xref:api/embeddings/postgresml-embeddings.adoc[PostgresML Embeddings]

== Spring CLI

The Spring CLI makes it easy to create new applications with code in your terminal window. Think of it as the 'create-react-app' of Spring for those familiar with the JavaScript ecosystem.

Download the latest https://github.com/spring-projects/spring-cli/releases[Spring CLI Release]
and follow the https://docs.spring.io/spring-cli/reference/installation.html#_setting_up_your_path_or_alias[instructions] to add `spring` to your `PATH`.

Create a simple AI application:

* For OpenAI

```shell
spring boot new ai
```

*  For Azure OpenAI

```shell
spring boot new ai-azure
```

You can also add the same simple AI application to your current project by using:

*  For OpenAI
```shell
spring boot add ai
```

*  For Azure OpenAI
```shell
spring boot add ai-azure
```

There is a project catalog available for Azure OpenAI that covers more functionality.
Add the catalog by running the the following command:

```shell
spring project-catalog add ai-azure
```

Now you have the following projects that you can use to create a new project by using the `spring boot new` command or add to your existing project by using the `spring boot add` command.

```shell
spring project list

├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-hello-world      │AI - Hello,    │https://github.com/rd-1-2022/ai-azure-openai-helloworld             │ai-azure│[java-17,      │
│                          │World          │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, web]    │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-templating│AI - Prompt    │https://github.com/rd-1-2022/ai-azure-prompt-template               │ai-azure│[java-17,      │
│                          │Templating     │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │templating]    │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-roles     │AI - Prompt    │https://github.com/rd-1-2022/ai-azure-openai-prompt-roles           │ai-azure│[java-17,      │
│                          │Templating     │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │roles]         │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-stuff-prompt     │AI - Stuff the │https://github.com/rd-1-2022/ai-azure-stuff-prompt                  │ai-azure│[java-17,      │
│                          │prompt         │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │stuff]         │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-rag       │AI - Retrieval │https://github.com/rd-1-2022/ai-azure-retrieval-augmented-generation│ai-azure│[java-17,      │
│                          │Augmented      │                                                                    │        │boot-3.1.x, ai,│
│                          │Generation     │                                                                    │        │azure,         │
│                          │               │                                                                    │        │retrieval]     │
└──────────────────────────┴───────────────┴────────────────────────────────────────────────────────────────────┴────────┴───────────────┘
```


== Sample Projects

You can clone these projects on GitHub to get started.

=== OpenAI

* https://github.com/rd-1-2022/ai-openai-helloworld

=== Azure OpenAI

* https://github.com/rd-1-2022/ai-azure-openai-helloworld
* https://github.com/rd-1-2022/ai-azure-stuff-prompt
* https://github.com/rd-1-2022/ai-azure-prompt-template
* https://github.com/rd-1-2022/ai-azure-openai-prompt-roles
* https://github.com/rd-1-2022/ai-azure-retrieval-augmented-generation

