[[getting-started]]
= Getting Started

This section offers jumping off points for how to get started using Spring AI.

[#_dependency_management]
== Dependency Management

The Spring AI project provides artifacts in the Spring Milestone and Snapshot repositories.

=== Bill of Materials

The Spring AI Bill of Materials (BOM) declares the recommended versions of all the dependencies used by a given release of Spring AI.
Using the BOM from your application’s build script avoids the need for you to specify and maintain the dependency versions yourself.
Instead, the version of the BOM you’re using determines the utilized dependency versions.
It also ensures that you’re using supported and tested versions of the dependencies by default, unless you choose to override them.

If you’re a Maven user, you can use the BOM by adding the following to your pom.xml file -

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-bom</artifactId>
            <version>{project-version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

Gradle users can also use the Spring AI BOM by leveraging Gradle (5.0+) native support for declaring dependency constraints using a Maven BOM.
This is implemented by adding a 'platform' dependency handler method to the dependencies section of your Gradle build script.
As shown in the snippet below this can then be followed by version-less declarations of the Starter Dependencies for the one or more spring-ai modules you wish to use, e.g. spring-ai-openai.

[source,gradle]
----
dependencies {
  implementation platform("org.springframework.ai:spring-ai-bom:${springAiVersion}")
  // Replace the following with the starter dependencies of specific modules you wish to use
  implementation 'org.springframework.ai:spring-ai-openai'
}
----

To use the Milestone and Snapshot version, you need to add references to the Spring Milestone and/or Snapshot repositories in your build file.

For Maven, add the following repository definitions as needed:

[source,xml]
----
  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
----

For Gradle, add the following repository definitions as needed:

[source,groovy]
----
repositories {
  mavenCentral()
  maven { url 'https://repo.spring.io/milestone' }
  maven { url 'https://repo.spring.io/snapshot' }
}
----

== Embeddings Models

* xref:api/embeddings.adoc[Embeddings API]
** xref:api/embeddings/openai-embeddings.adoc[Spring AI OpenAI Embeddings]
** xref:api/embeddings/azure-openai-embeddings.adoc[Spring AI Azure OpenAI Embeddings]
** xref:api/embeddings/ollama-embeddings.adoc[Spring AI Ollama Embeddings]
** xref:api/embeddings/onnx.adoc[Spring AI Transformers (ONNX) Embeddings]
** xref:api/embeddings/postgresml-embeddings.adoc[Spring AI PostgresML Embeddings]
** xref:api/embeddings/bedrock-cohere-embedding.adoc[Spring AI Bedrock Cohere Embeddings]
** xref:api/embeddings/bedrock-titan-embedding.adoc[Spring AI Bedrock Titan Embeddings]
** xref:api/embeddings/vertexai-embeddings.adoc[Spring AI VertexAI Embeddings]

== Chat Models
* xref:api/chatclient.adoc[Chat Completion API]
** xref:api/clients/openai-chat.adoc[OpenAI Chat Completion]
** xref:api/clients/azure-openai-chat.adoc[Microsoft Azure Open AI Chat Completion]
** xref:api/clients/ollama-chat.adoc[Ollama Chat Completion]
** xref:api/clients/huggingface.adoc[HuggingFace Chat Completion] (no streaming support)
** xref:api/clients/vertexai-chat.adoc[Google Vertex Chat Completion] (no streaming support)
** xref:api/bedrock.adoc[Amazon Bedrock]
*** xref:api/clients/bedrock/bedrock-cohere.adoc[Cohere Chat Completion]
*** xref:api/clients/bedrock/bedrock-llama2.adoc[Llama2 Chat Completion]
*** xref:api/clients/bedrock/bedrock-titan.adoc[Titan Chat Completion]
*** xref:api/clients/bedrock/bedrock-anthropic.adoc[Anthropic Chat Completion]
// ** xref:api/clients/bedrock/bedrock-jurassic.adoc[Jurassic2 Chat Completion] (WIP, no streaming support)

== Image Generation Models
* xref:api/imageclient.adoc[]
** xref:api/clients/image/openai-image.adoc[OpenAI Image Generation]
** xref:api/clients/image/stabilityai-image.adoc[StabilityAI Image Generation]

== Vector Databases
* xref:api/vectordbs.adoc[Vector Database API]
** xref:api/vectordbs/azure.adoc[ Azure Vector Search] - The https://learn.microsoft.com/en-us/azure/search/vector-search-overview[Azure] vector store.
** xref:api/vectordbs/chroma.adoc[ChromaVectorStore] - The https://www.trychroma.com/[Chroma] vector store.
** xref:api/vectordbs/milvus.adoc[MilvusVectorStore] - The https://milvus.io/[Milvus] vector store.
** xref:api/vectordbs/neo4j.adoc[Neo4jVectorStore] - The https://neo4j.com/[Neo4j] vector store.
** xref:api/vectordbs/pgvector.adoc[PgVectorStore] - The https://github.com/pgvector/pgvector[PostgreSQL/PGVector] vector store.
** xref:api/vectordbs/pinecone.adoc[PineconeVectorStore] - https://www.pinecone.io/[PineCone] vector store.
** xref:api/vectordbs/redis.adoc[RedisVectorStore] - The https://redis.io/[Redis] vector store.
** xref:api/vectordbs/weaviate.adoc[WeaviateVectorStore] - The https://weaviate.io/[Weaviate] vector store.
** link:https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/vectorstore/SimpleVectorStore.java[SimpleVectorStore] - A simple (in-memory) implementation of persistent vector storage, good for educational purposes.


== Spring CLI

The Spring CLI makes it easy to create new applications with code in your terminal window. Think of it as the 'create-react-app' of Spring for those familiar with the JavaScript ecosystem.

Download the latest https://github.com/spring-projects/spring-cli/releases[Spring CLI Release]
and follow the https://docs.spring.io/spring-cli/reference/installation.html#_setting_up_your_path_or_alias[instructions] to add `spring` to your `PATH`.

Create a simple AI application:

* For OpenAI

```shell
spring boot new ai
```

*  For Azure OpenAI

```shell
spring boot new ai-azure
```

You can also add the same simple AI application to your current project by using:

*  For OpenAI
```shell
spring boot add ai
```

*  For Azure OpenAI
```shell
spring boot add ai-azure
```

There is a project catalog available for Azure OpenAI that covers more functionality.
Add the catalog by running the the following command:

```shell
spring project-catalog add ai-azure
```

Now you have the following projects that you can use to create a new project by using the `spring boot new` command or add to your existing project by using the `spring boot add` command.

```shell
spring project list

├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-hello-world      │AI - Hello,    │https://github.com/rd-1-2022/ai-azure-openai-helloworld             │ai-azure│[java-17,      │
│                          │World          │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, web]    │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-templating│AI - Prompt    │https://github.com/rd-1-2022/ai-azure-prompt-template               │ai-azure│[java-17,      │
│                          │Templating     │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │templating]    │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-roles     │AI - Prompt    │https://github.com/rd-1-2022/ai-azure-openai-prompt-roles           │ai-azure│[java-17,      │
│                          │Templating     │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │roles]         │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-stuff-prompt     │AI - Stuff the │https://github.com/rd-1-2022/ai-azure-stuff-prompt                  │ai-azure│[java-17,      │
│                          │prompt         │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │stuff]         │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-rag       │AI - Retrieval │https://github.com/rd-1-2022/ai-azure-retrieval-augmented-generation│ai-azure│[java-17,      │
│                          │Augmented      │                                                                    │        │boot-3.1.x, ai,│
│                          │Generation     │                                                                    │        │azure,         │
│                          │               │                                                                    │        │retrieval]     │
└──────────────────────────┴───────────────┴────────────────────────────────────────────────────────────────────┴────────┴───────────────┘
```


== Sample Projects

You can clone these projects on GitHub to get started.

=== OpenAI

* https://github.com/rd-1-2022/ai-openai-helloworld

=== Azure OpenAI

* https://github.com/rd-1-2022/ai-azure-openai-helloworld
* https://github.com/rd-1-2022/ai-azure-stuff-prompt
* https://github.com/rd-1-2022/ai-azure-prompt-template
* https://github.com/rd-1-2022/ai-azure-openai-prompt-roles
* https://github.com/rd-1-2022/ai-azure-retrieval-augmented-generation

