= Getting Started

== API Keys

=== OpenAI

Create an account at link:https://platform.openai.com/signup[OpenAI Signup] and generate the token at link:https://platform.openai.com/account/api-keys[API Keys].

The Spring AI project defines a configuration property named `spring.ai.openai.api-key` that you should set to the value of the `API Key` obtained from `openai.com`.

Exporting an environment variable is one way to set that configuration property.

[source,shell]
----
export SPRING_AI_OPENAI_API_KEY=<INSERT KEY HERE>
----

=== Azure OpenAI
Obtain your Azure OpenAI `endpoint` and `api-key` from the Azure OpenAI Service section on link:https://portal.azure.com[Azure Portal].

The Spring AI project defines a configuration property named `spring.ai.azure.openai.api-key` that you should set to the value of the `API Key` obtained from Azure.

Exporting environment variables is one way to set these configuration properties.

[source,shell]
----
export SPRING_AI_AZURE_OPENAI_API_KEY=<INSERT KEY HERE>
export SPRING_AI_AZURE_OPENAI_ENDPOINT=<INSERT ENDPOINT URL HERE>
----

== Dependencies

The Spring AI project provides artifacts in the Spring Milestone Repository.
You will need to add configuration to add a reference to the Spring Milestone repository in your build file.
For example, in maven, add the following repository definition.

[source,xml]
----
  <repositories>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
----

Add the Spring Boot Starter depending on if you are using Azure Open AI or Open AI.

* Azure OpenAI
[source, xml]
----
    <dependency>
        <groupId>org.springframework.experimental.ai</groupId>
        <artifactId>spring-ai-azure-openai-spring-boot-starter</artifactId>
        <version>0.2.0-SNAPSHOT</version>
    </dependency>
----

* OpenAI

[source, xml]
----
    <dependency>
        <groupId>org.springframework.experimental.ai</groupId>
        <artifactId>spring-ai-openai-spring-boot-starter</artifactId>
        <version>0.2.0-SNAPSHOT</version>
    </dependency>
----

== Spring CLI

The Spring CLI makes it easy to create new applications with code in your terminal window.  Think of it as the 'create-react-app' of Spring for those familiar with the JavaScript ecosystem.

Download the latest https://github.com/spring-projects-experimental/spring-cli/releases[Spring CLI Release]

and follow the https://docs.spring.io/spring-cli/reference/installation.html#_setting_up_your_path_or_alias[instructions] to add `spring` to your `PATH`.

Create a simple AI application

* For OpenAI

```shell
spring boot new ai
```

or

*  For Azure OpenAI

```shell
spring boot new ai-azure
```

You can also `ADD` the same simple AI application to your current project using

*  For OpenAI
```shell
spring boot add ai
```

or

*  For Azure OpenAI
```shell
spring boot add ai-azure
```

There is a project catalog available for Azure OpenAI that covers more functionality.
Add the catalog by running the command

* For Azure Open AI

```shell
spring project-catalog add ai-azure
```

Now you have the following projects that you can use to create a new project using the `spring boot new` command or add to your existing project using the `spring boot add` command.

```shell
spring project list

├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-hello-world      │AI - Hello,    │https://github.com/rd-1-2022/ai-azure-openai-helloworld             │ai-azure│[java-17,      │
│                          │World          │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, web]    │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-templating│AI - Prompt    │https://github.com/rd-1-2022/ai-azure-prompt-template               │ai-azure│[java-17,      │
│                          │Templating     │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │templating]    │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-roles     │AI - Prompt    │https://github.com/rd-1-2022/ai-azure-openai-prompt-roles           │ai-azure│[java-17,      │
│                          │Templating     │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │roles]         │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-stuff-prompt     │AI - Stuff the │https://github.com/rd-1-2022/ai-azure-stuff-prompt                  │ai-azure│[java-17,      │
│                          │prompt         │                                                                    │        │boot-3.1.x, ai,│
│                          │               │                                                                    │        │azure, prompt  │
│                          │               │                                                                    │        │stuff]         │
├──────────────────────────┼───────────────┼────────────────────────────────────────────────────────────────────┼────────┼───────────────┤
│ai-azure-prompt-rag       │AI - Retrieval │https://github.com/rd-1-2022/ai-azure-retrieval-augmented-generation│ai-azure│[java-17,      │
│                          │Augmented      │                                                                    │        │boot-3.1.x, ai,│
│                          │Generation     │                                                                    │        │azure,         │
│                          │               │                                                                    │        │retrieval]     │
└──────────────────────────┴───────────────┴────────────────────────────────────────────────────────────────────┴────────┴───────────────┘
```


== Sample Projects

You can clone these projects on GitHub to get started.

=== OpenAI

* https://github.com/rd-1-2022/ai-openai-helloworld

=== Azure OpenAI

* https://github.com/rd-1-2022/ai-azure-openai-helloworld
* https://github.com/rd-1-2022/ai-azure-stuff-prompt
* https://github.com/rd-1-2022/ai-azure-prompt-template
* https://github.com/rd-1-2022/ai-azure-openai-prompt-roles
* https://github.com/rd-1-2022/ai-azure-retrieval-augmented-generation

