[[introduction]]
= Spring AI

The Spring AI project aims to streamline the development of applications that incorporate artificial intelligence functionality without unnecessary complexity.

The project draws inspiration from notable Python projects, such as LangChain and LlamaIndex, but Spring AI is not a direct port of those projects.
The project was founded with the belief that the next wave of Generative AI applications will not be only for Python developers but will be ubiquitous across many programming languages.

At its core, Spring AI provides abstractions that serve as the foundation for developing AI applications.
These abstractions have multiple implementations, enabling easy component swapping with minimal code changes.
For example, Spring AI introduces the `ChatClient` interface with implementations for OpenAI and Azure OpenAI.

In addition to these core abstractions, Spring AI aims to provide higher-level functionalities to address common use cases such as "`Q&A over your documentation`" or "`Chat with your documentation.`"
As the complexity of the use cases increases, the Spring AI project will integrate with other projects in the Spring Ecosystem, such as Spring Integration, Spring Batch, and Spring Data.

To simplify setup, Spring Boot starters are available to help set up essential dependencies and classes.
There is also a collection of sample applications to help you explore the project's features.
Lastly, the new Spring CLI project also enables you to get started quickly by using the `spring boot new ai` command for new projects or `spring boot add ai` for adding AI capabilities to your existing application.

The xref:concepts.adoc[next section] provides a high-level overview of AI concepts and their representation in Spring AI.
The xref:getting-started.adoc[Getting Started] section shows you how to create your first AI application.
Subsequent sections delve into each component and common use cases with a code-focused approach.
