changelog:
  issues:
    generate_links: true
contributors:
  exclude:
    names:
      - "tzolov"
      - "sdeleuze"
      - "ilayaperumalg"
      - "ericbottard"
      - "sobychacko"
      - "dimitarproynov"
