= Yi AI Chat

Spring AI supports the various AI language models from Yi AI. You can interact with Yi AI language models and create a multilingual conversational assistant based on YiAI models.

== Prerequisites

You will need to create an API with YiAI to access Yi AI language models.

Create an account at https://platform.lingyiwanwu.com/login[Yi AI registration page] and generate the token on the https://platform.lingyiwanwu.com/apikeys[API Keys page].
The Spring AI project defines a configuration property named `spring.ai.yi.api-key` that you should set to the value of the `API Key` obtained from https://platform.lingyiwanwu.com/apikeys[API Keys page].
Exporting an environment variable is one way to set that configuration property:

[source,shell]
----
export SPRING_AI_YI_AI_API_KEY=<INSERT KEY HERE>
----

=== Add Repositories and BOM

Spring AI artifacts are published in Spring Milestone and Snapshot repositories.
Refer to the xref:getting-started.adoc#repositories[Repositories] section to add these repositories to your build system.

To help with dependency management, Spring AI provides a BOM (bill of materials) to ensure that a consistent version of Spring AI is used throughout the entire project. Refer to the xref:getting-started.adoc#dependency-management[Dependency Management] section to add the Spring AI BOM to your build system.



== Auto-configuration

Spring AI provides Spring Boot auto-configuration for the YiAI Chat Client.
To enable it add the following dependency to your project's Maven `pom.xml` file:

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-yi-spring-boot-starter</artifactId>
</dependency>
----

or to your Gradle `build.gradle` build file.

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-yi-spring-boot-starter'
}
----

TIP: Refer to the xref:getting-started.adoc#dependency-management[Dependency Management] section to add the Spring AI BOM to your build file.

=== Chat Properties

==== Retry Properties

The prefix `spring.ai.retry` is used as the property prefix that lets you configure the retry mechanism for the Yi AI chat model.

[cols="3,5,1"]
|====
| Property | Description | Default

| spring.ai.retry.max-attempts   | Maximum number of retry attempts. |  10
| spring.ai.retry.backoff.initial-interval | Initial sleep duration for the exponential backoff policy. |  2 sec.
| spring.ai.retry.backoff.multiplier | Backoff interval multiplier. |  5
| spring.ai.retry.backoff.max-interval | Maximum backoff duration. |  3 min.
| spring.ai.retry.on-client-errors | If false, throw a NonTransientAiException, and do not attempt retry for `4xx` client error codes | false
| spring.ai.retry.exclude-on-http-codes | List of HTTP status codes that should not trigger a retry (e.g. to throw NonTransientAiException). | empty
| spring.ai.retry.on-http-codes | List of HTTP status codes that should trigger a retry (e.g. to throw TransientAiException). | empty
|====

==== Connection Properties

The prefix `spring.ai.yi` is used as the property prefix that lets you connect to YiAI.

[cols="3,5,1"]
|====
| Property | Description | Default

| spring.ai.yi.base-url   | The URL to connect to |  https://api.lingyiwanwu.com
| spring.ai.yi.api-key    | The API Key           |  -
|====

==== Configuration Properties

The prefix `spring.ai.yi.chat` is the property prefix that lets you configure the chat model implementation for YiAI.

[cols="3,5,1"]
|====
| Property | Description | Default

| spring.ai.yi.chat.enabled | Enable YiAI chat model.  | true
| spring.ai.yi.chat.base-url | Optional overrides the spring.ai.yi.base-url to provide chat specific url |  https://api.lingyiwanwu.com
| spring.ai.yi.chat.api-key | Optional overrides the spring.ai.yi.api-key to provide chat specific api-key |  -
| spring.ai.yi.chat.options.model | This is the YiAI Chat model to use | `YI_LARGE` (the `YI_LARGE`, `YI_MEDIUM`, `YI_MEDIUM`, `YI_VISION`, `YI_SPARK`, `YI_LARGE_RAG`, and `YI_LARGE_TURBO` point to the latest model versions)
| spring.ai.yi.chat.options.maxTokens | Specify the maximum number of tokens for the model when generating content. This defines the upper limit for generation, but does not guarantee that this number will be generated each time. | -
| spring.ai.yi.chat.options.temperature | Controls the divergence and centralization of the generated results. The smaller the value, the more centralized; the larger the value, the more divergent. Range of values: between 0 and 2. | 0.9
| spring.ai.yi.chat.options.topP | Control the randomness of the generated results. The smaller the value, the weaker the randomness; the larger the value, the stronger the randomness. Value range: between 0 and 1. | 0.3
|====

NOTE: You can override the common `spring.ai.yi.base-url` and `spring.ai.yi.api-key` for the `ChatModel` implementations.
The `spring.ai.yi.chat.base-url` and `spring.ai.yi.chat.api-key` properties if set take precedence over the common properties.
This is useful if you want to use different YiAI accounts for different models and different model endpoints.

TIP: All properties prefixed with `spring.ai.yi.chat.options` can be overridden at runtime by adding a request specific <<chat-options>> to the `Prompt` call.

== Runtime Options [[chat-options]]

The link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-yi/src/main/java/org/springframework/ai/yi/YiAiChatOptions.java[YiAiChatOptions.java] provides model configurations, such as the model to use, the temperature, the frequency penalty, etc.

On start-up, the default options can be configured with the `YiAiChatModel(api, options)` constructor or the `spring.ai.yi.chat.options.*` properties.

At run-time you can override the default options by adding new, request specific, options to the `Prompt` call.
For example to override the default model and temperature for a specific request:

[source,java]
----
ChatResponse response = chatModel.call(
    new Prompt(
        "Generate the names of 5 famous pirates.",
        YiAiChatOptions.builder()
            .withModel(YiAiApi.ChatModel.YI_LARGE.getValue())
            .withTemperature(0.9f)
        .build()
    ));
----

TIP: In addition to the model specific link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-yi/src/main/java/org/springframework/ai/yi/YiAiChatOptions.java[YiAiChatOptions] you can use a portable https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/chat/ChatOptions.java[ChatOptions] instance, created with the https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/chat/ChatOptionsBuilder.java[ChatOptionsBuilder#builder()].

== Sample Controller

https://start.spring.io/[Create] a new Spring Boot project and add the `spring-ai-yi-spring-boot-starter` to your pom (or gradle) dependencies.

Add a `application.properties` file, under the `src/main/resources` directory, to enable and configure the YiAi chat model:

[source,application.properties]
----
spring.ai.yi.api-key=YOUR_API_KEY
spring.ai.yi.chat.options.model=yi-large
spring.ai.yi.chat.options.temperature=0.9
----

TIP: replace the `api-key` with your YiAI credentials.

This will create a `YiAiChatModel` implementation that you can inject into your class.
Here is an example of a simple `@Controller` class that uses the chat model for text generations.

[source,java]
----
@RestController
public class ChatController {

    private final YiAiChatModel chatModel;

    @Autowired
    public ChatController(YiAiChatModel chatModel) {
        this.chatModel = chatModel;
    }

    @GetMapping("/ai/generate")
    public Map generate(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        return Map.of("generation", chatModel.call(message));
    }

    @GetMapping("/ai/generateStream")
	public Flux<ChatResponse> generateStream(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        var prompt = new Prompt(new UserMessage(message));
        return chatModel.stream(prompt);
    }
}
----

== Manual Configuration

The link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-yi/src/main/java/org/springframework/ai/yi/YiAiChatModel.java[YiAiChatModel] implements the `ChatModel` and `StreamingChatModel` and uses the <<low-level-api>> to connect to the YiAI service.

Add the `spring-ai-yi` dependency to your project's Maven `pom.xml` file:

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-yi</artifactId>
</dependency>
----

or to your Gradle `build.gradle` build file.

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-yi'
}
----

TIP: Refer to the xref:getting-started.adoc#dependency-management[Dependency Management] section to add the Spring AI BOM to your build file.

Next, create a `YiAiChatModel` and use it for text generations:

[source,java]
----
var yiAiApi = new YiAiApi(System.getenv("YI_AI_API_KEY"));

var chatModel = new YiAiChatModel(yiAiApi, YiAiChatOptions.builder()
                .withModel(yiAiApi.ChatModel.YI_LARGE.getValue())
                .withTemperature(0.9f)
                .withMaxTokens(100)
                .build());

ChatResponse response = chatModel.call(
    new Prompt("Generate the names of 5 famous pirates."));

// Or with streaming responses
Flux<ChatResponse> streamResponse = chatModel.stream(
    new Prompt("Generate the names of 5 famous pirates."));
----

The `YiAiChatOptions` provides the configuration information for the chat requests.
The `YiAiChatOptions.Builder` is fluent options builder.

=== Low-level YiAiApi Client [[low-level-api]]

The link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-yi/src/main/java/org/springframework/ai/yi/api/YiAiApi.java[YiAiApi] provides is lightweight Java client for link:https://platform.lingyiwanwu.com/docs#create-chat-completion[Yi AI API].

Here is a simple snippet how to use the api programmatically:

[source,java]
----
YiAiApi yiAiApi =
    new YiAiApi(System.getenv("YI_AI_API_KEY"));

ChatCompletionMessage chatCompletionMessage =
    new ChatCompletionMessage("Hello world", Role.USER);

// Sync request
ResponseEntity<ChatCompletion> response = yiAiApi.chatCompletionEntity(
    new ChatCompletionRequest(List.of(chatCompletionMessage), yiAiApi.ChatModel.YI_LARGE.getValue(), 0.9f, false));

// Streaming request
Flux<ChatCompletionChunk> streamResponse = zhiPyiAiApiuAiApi.chatCompletionStream(
        new ChatCompletionRequest(List.of(chatCompletionMessage), yiAiApi.ChatModel.YI_LARGE.getValue(), 0.9f, true));
----

Follow the https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-yi/src/main/java/org/springframework/ai/yi/api/YiAiApi.java[YiAiApi.java]'s JavaDoc for further information.

==== YiAiApi Samples
* The link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-yi/src/test/java/org/springframework/ai/yi/api/YiAiApiIT.java[YiAiApiIT.java] test provides some general examples how to use the lightweight library.