/*
 * Copyright 2023 - 2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.ai.vertexai.anthropic.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param id Unique object identifier. The format and length of IDs may change over time.
 * @param type Object type. For Messages, this is always "message".
 * @param role Conversational role of the generated message. This will always be
 * "assistant".
 * @param content Content generated by the model. This is an array of content blocks.
 * @param model The model that handled the request.
 * @param stopReason The reason the model stopped generating tokens. This will be one of
 * "end_turn", "max_tokens", "stop_sequence", "tool_use", or "timeout".
 * @param stopSequence Which custom stop sequence was generated, if any.
 * @param usage Input and output token usage.
 * @author Alessio Bertazzo
 * @since 1.0.0
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ChatCompletionResponse(
// @formatter:off
									  @JsonProperty("id") String id,
									  @JsonProperty("type") String type,
									  @JsonProperty("role") Role role,
									  @JsonProperty("content") List<ContentBlock> content,
									  @JsonProperty("model") String model,
									  @JsonProperty("stop_reason") String stopReason,
									  @JsonProperty("stop_sequence") String stopSequence,
									  @JsonProperty("usage") ApiUsage usage) {
	// @formatter:on
}