/*
 * Copyright 2025-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.ai.vertexai.imagen;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import org.springframework.ai.image.ImageOptions;

import static org.springframework.ai.vertexai.imagen.VertexAiImagenUtils.calculateDimensionsFromAspectRatio;

/**
 * Options for the Vertex AI Image service.
 *
 * @author Sami Marzouki
 */
public class VertexAiImagenImageOptions implements ImageOptions {

	public static final String DEFAULT_MODEL_NAME = VertexAiImagenImageModelName.IMAGEN_2_V006.getValue();

	/**
	 * Required: int
	 * The number of images to generate. The default value is 4. The
	 * imagen-3.0-generate-001 model supports values 1 through 4. The
	 * imagen-3.0-fast-generate-001 model supports values 1 through 4. The
	 * imagegeneration@006 model supports values 1 through 4. The imagegeneration@005
	 * model supports values 1 through 4. The imagegeneration@002 model supports values 1
	 * through 8.
	 */
	@JsonProperty("sampleCount")
	private Integer n;

	/**
	 * The model to use for image generation.
	 */
	@JsonProperty("model")
	private String model;

	/**
	 * Optional: Uint32
	 * The random seed for image generation. This is not available when addWatermark is set to true.
	 */
	@JsonProperty("seed")
	private Integer seed;

	/**
	 * Optional: string
	 * A description of what to discourage in the generated images.
	 * The imagen-3.0-generate-001 model supports up to 480 tokens.
	 * The imagen-3.0-fast-generate-001 model supports up to 480 tokens.
	 * The imagegeneration@006 model supports up to 128 tokens.
	 * The imagegeneration@005 model supports up to 128 tokens.
	 * The imagegeneration@002 model supports up to 64 tokens.
	 */
	@JsonProperty("negativePrompt")
	private String negativePrompt;

	/**
	 * Optional: string
	 * The aspect ratio for the image. The default value is "1:1".
	 * The imagen-3.0-generate-001 model supports "1:1", "9:16", "16:9", "3:4", or "4:3".
	 * The imagen-3.0-fast-generate-001 model supports "1:1", "9:16", "16:9", "3:4", or "4:3".
	 * The imagegeneration@006 model supports "1:1", "9:16", "16:9", "3:4", or "4:3".
	 * The imagegeneration@005 model supports "1:1" or "9:16".
	 * The imagegeneration@002 model supports "1:1".
	 */
	@JsonProperty("aspectRatio")
	private String aspectRatio;

	/**
	 * Optional: outputOptions
	 * Describes the output image format in an outputOptions object.
	 *
	 * @see OutputOptions
	 */
	@JsonProperty("outputOptions")
	private OutputOptions outputOptions;

	/**
	 * Optional: string (imagegeneration@002 only)
	 * Describes the style for the generated images. The following values are supported:
	 * "photograph", "digital_art", "landscape", "sketch", "watercolor", "cyberpunk", "pop_art".
	 */
	@JsonProperty("sampleImageStyle")
	private String style;

	/**
	 * Optional: string (imagen-3.0-generate-001, imagen-3.0-fast-generate-001, and imagegeneration@006 only)
	 * Allow generation of people by the model. The following values are supported:
	 * "dont_allow": Disallow the inclusion of people or faces in images.
	 * "allow_adult": Allow generation of adults only.
	 * "allow_all": Allow generation of people of all ages.
	 * The default value is "allow_adult".
	 */
	@JsonProperty("personGeneration")
	private String personGeneration;

	/**
	 * Optional: string (imagen-3.0-generate-001, imagen-3.0-fast-generate-001, and imagegeneration@006 only)
	 * Adds a filter level to safety filtering. The following values are supported:
	 * "block_low_and_above": Strongest filtering level, most strict blocking. Deprecated value: "block_most".
	 * "block_medium_and_above": Block some problematic prompts and responses. Deprecated value: "block_some".
	 * "block_only_high": Reduces the number of requests blocked due to safety filters. May increase objectionable
	 * content generated by Imagen. Deprecated value: "block_few".
	 * "block_none": Block very few problematic prompts and responses. Access to this feature is restricted.
	 * Previous field value: "block_fewest".
	 * The default value is "block_medium_and_above".
	 */
	@JsonProperty("safetySetting")
	private String safetySetting;

	/**
	 * Optional: bool
	 * Add an invisible watermark to the generated images.
	 * The default value is false for the imagegeneration@002 and imagegeneration@005 models,
	 * and true for the imagen-3.0-fast-generate-001, imagegeneration@006, and imagegeneration@006 models.
	 */
	@JsonProperty("addWatermark")
	private Boolean addWatermark;

	/**
	 * Optional: string
	 * Cloud Storage URI to store the generated images.
	 */
	@JsonProperty("storageUri")
	private String storageUri;

	private List<Integer> size;

	public static Builder builder() {
		return new Builder();
	}

	@Override
	public Integer getN() {
		return this.n;
	}

	public void setN(Integer n) {
		this.n = n;
	}

	@Override
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Override
	public Integer getWidth() {
		if (this.size == null || this.size.isEmpty()) {
			return null;
		}
		return this.size.get(0);
	}

	@Override
	public Integer getHeight() {
		if (this.size == null || this.size.isEmpty()) {
			return null;
		}
		return this.size.get(1);
	}

	@Override
	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	@Override
	public String getResponseFormat() {
		if (this.outputOptions == null) {
			return null;
		}
		return this.outputOptions.mimeType;
	}

	public Integer getCompressionQuality() {
		if (this.outputOptions == null) {
			return null;
		}
		return this.outputOptions.compressionQuality;
	}

	public OutputOptions getOutputOptions() {
		return this.outputOptions;
	}

	public Integer getSeed() {
		return seed;
	}

	public void setSeed(Integer seed) {
		this.seed = seed;
	}

	public String getNegativePrompt() {
		return negativePrompt;
	}

	public void setNegativePrompt(String negativePrompt) {
		this.negativePrompt = negativePrompt;
	}

	public String getAspectRatio() {
		return aspectRatio;
	}

	public void setAspectRatio(String aspectRatio) {
		this.aspectRatio = aspectRatio;
	}

	public String getPersonGeneration() {
		return personGeneration;
	}

	public void setPersonGeneration(String personGeneration) {
		this.personGeneration = personGeneration;
	}

	public String getSafetySetting() {
		return safetySetting;
	}

	public void setSafetySetting(String safetySetting) {
		this.safetySetting = safetySetting;
	}

	public Boolean getAddWatermark() {
		return addWatermark;
	}

	public void setAddWatermark(Boolean addWatermark) {
		this.addWatermark = addWatermark;
	}

	public String getStorageUri() {
		return storageUri;
	}

	public void setStorageUri(String storageUri) {
		this.storageUri = storageUri;
	}

	public void setSize(List<Integer> size) {
		this.size = size;
	}

	public static final class OutputOptions {

		@JsonProperty("mimeType")
		private String mimeType;

		@JsonProperty("compressionQuality")
		private Integer compressionQuality;

		public static Builder builder() {
			return new Builder();
		}

		public String getMimeType() {
			return mimeType;
		}

		public void setMimeType(String mimeType) {
			this.mimeType = mimeType;
		}

		public Integer getCompressionQuality() {
			return compressionQuality;
		}

		public void setCompressionQuality(Integer compressionQuality) {
			this.compressionQuality = compressionQuality;
		}

		public static final class Builder {

			private final OutputOptions options;

			private Builder() {
				this.options = new OutputOptions();
			}

			public Builder mimeType(String format) {
				this.options.setMimeType(format);
				return this;
			}

			public Builder compressionQuality(Integer compressionQuality) {
				this.options.setCompressionQuality(compressionQuality);
				return this;
			}

			public OutputOptions build() {
				return this.options;
			}
		}
	}

	public static final class Builder {

		private final VertexAiImagenImageOptions options;

		private Builder() {
			this.options = new VertexAiImagenImageOptions();
		}

		public Builder from(VertexAiImagenImageOptions fromOptions) {
			if (fromOptions.getN() != null) {
				this.options.setN(fromOptions.getN());
			}
			if (fromOptions.getModel() != null) {
				this.options.setModel(fromOptions.getModel());
			}
			if (fromOptions.getAspectRatio() != null) {
				this.options.setAspectRatio(fromOptions.getAspectRatio());
				this.options.setSize(calculateDimensionsFromAspectRatio(fromOptions.getAspectRatio()));
			}
			if (fromOptions.getStyle() != null) {
				this.options.setStyle(fromOptions.getStyle());
			}
			if (fromOptions.getOutputOptions() != null) {
				if (fromOptions.getResponseFormat() != null) {
					this.options.outputOptions.setMimeType(fromOptions.getResponseFormat());
				}
				if (fromOptions.getCompressionQuality() != null) {
					this.options.outputOptions.setCompressionQuality(fromOptions.getCompressionQuality());
				}
			}
			if (fromOptions.getSeed() != null) {
				this.options.setSeed(fromOptions.getSeed());
			}
			if (fromOptions.getNegativePrompt() != null) {
				this.options.setNegativePrompt(fromOptions.getNegativePrompt());
			}
			if (fromOptions.getPersonGeneration() != null) {
				this.options.setPersonGeneration(fromOptions.getPersonGeneration());
			}
			if (fromOptions.getSafetySetting() != null) {
				this.options.setSafetySetting(fromOptions.getSafetySetting());
			}
			if (fromOptions.getAddWatermark() != null) {
				this.options.setAddWatermark(fromOptions.getAddWatermark());
			}
			if (fromOptions.getStorageUri() != null) {
				this.options.setStorageUri(fromOptions.getStorageUri());
			}

			return this;
		}

		public Builder N(Integer n) {
			this.options.setN(n);
			return this;
		}

		public Builder model(String model) {
			this.options.setModel(model);
			return this;
		}

		public Builder seed(Integer seed) {
			this.options.setSeed(seed);
			return this;
		}

		public Builder negativePrompt(String negativePrompt) {
			this.options.setNegativePrompt(negativePrompt);
			return this;
		}

		public Builder aspectRatio(String aspectRatio) {
			this.options.setAspectRatio(aspectRatio);
			this.options.setSize(calculateDimensionsFromAspectRatio(aspectRatio));
			return this;
		}

		public Builder outputOptions(OutputOptions outputOptions) {
			this.options.outputOptions = outputOptions;
			return this;
		}

		public Builder personGeneration(String personGeneration) {
			this.options.setPersonGeneration(personGeneration);
			return this;
		}

		public Builder safetySetting(String safetySetting) {
			this.options.setSafetySetting(safetySetting);
			return this;
		}

		public Builder addWatermark(Boolean addWatermark) {
			this.options.setAddWatermark(addWatermark);
			return this;
		}

		public Builder storageUri(String storageUri) {
			this.options.setStorageUri(storageUri);
			return this;
		}

		public Builder style(String style) {
			this.options.setStyle(style);
			return this;
		}

		public VertexAiImagenImageOptions build() {
			return this.options;
		}

	}
}
