package org.springframework.ai.model;

import java.util.List;

/**
 * Interface representing the response received from an AI model. This interface provides
 * methods to access the main result or a list of results generated by the AI model, along
 * with the response metadata. It serves as a standardized way to encapsulate and manage
 * the output from AI models, ensuring easy retrieval and processing of the generated
 * information.
 *
 * @param <T> the type of the result(s) provided by the AI model
 * @author Mark Pollack
 * @since 0.8.0
 */
public interface ModelResponse<T extends ModelResult<?>> {

	/**
	 * Retrieves the result of the AI model.
	 * @param <T> the type of the result generated by the AI model
	 * @return the result generated by the AI model
	 */
	T getResult();

	/**
	 * Retrieves the list of generated outputs by the AI model.
	 * @param <T> the type of the generated outputs
	 * @return the list of generated outputs
	 */
	List<T> getResults();

	/**
	 * Retrieves the response metadata associated with the AI model's response.
	 * @return the response metadata
	 */
	ResponseMetadata getMetadata();

}
