package org.springframework.ai.model;

/**
 * Interface representing metadata associated with the results of an AI model. This
 * interface focuses on providing additional context and insights into the results
 * generated by AI models. It could include information like computation time, model
 * version, or other relevant details that enhance understanding and management of AI
 * model outputs in various applications.
 *
 * @author Mark Pollack
 * @since 0.8.0
 */
public interface ResultMetadata {

}
