= Amazon Bedrock Anthropic

https://ai.meta.com/llama/[Meta's Llama 2 Chat] is part of the Llama 2 collection of large language models.
It excels in dialogue-based applications with a parameter scale ranging from 7 billion to 70 billion.
Leveraging public datasets and over 1 million human annotations, Llama Chat offers context-aware dialogues.

Trained on 2 trillion tokens from public data sources, Llama-2-Chat provides extensive knowledge for insightful conversations.
Rigorous testing, including over 1,000 hours of red-teaming and annotation, ensures both performance and safety, making it a reliable choice for AI-driven dialogues.

The https://aws.amazon.com/bedrock/llama-2/[AWS Llama 2 Model Page] and https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html[Amazon Bedrock User Guide] contains detailed information on how to use the AWS hosted model.


== Getting Started

Refer to the xref:api/clients/bedrock.adoc[Spring AI documentation on Amazon Bedrock] for setting up API access.

== Project Dependencies

Refer to the xref:getting-started.adoc#_dependency_management[Dependency Management] section to add Milestone and/or Snapshot Repositories to your build file.

Then add the Spring Boot Starter dependency to your project's Maven `pom.xml` build file:

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-bedrock-ai-spring-boot-starter</artifactId>
    <version>0.8.0-SNAPSHOT</version>
</dependency>
----

or to your Gradle `build.gradle` build file.

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-bedrock-ai-spring-boot-starter:0.8.0-SNAPSHOT'
}
----

== Enable Anthropic Support

Spring AI defines a configuration property named `spring.ai.bedrock.anthropic.chat.enabled` that you should set to `true` to enable support for Anthropic.

Exporting environment variables in one way to set this configuration property.

[source,shell]
----
export SPRING_AI_BEDROCK_ANTHROPIC_CHAT_ENABLED=true
----

== Sample Code

This will create a `ChatClient` implementation that you can inject into your class.
Here is an example of a simple `@Controller` class that uses the `ChatClient` implementation.

[source,java]
----
@RestController
public class ChatController {

    private final ChatClient chatClient;

    @Autowired
    public ChatController(ChatClient chatClient) {
        this.chatClient = chatClient;
    }

    @GetMapping("/ai/generate")
    public Map generate(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        return Map.of("generation", chatClient.generate(message));
    }
}
----

== Bedrock Properties

The prefix `spring.ai.bedrock.aws` is the property prefix to configure the connection to AWS Bedrock.


[cols="3,3,3"]
|====
| Property | Description | Default

| spring.ai.bedrock.aws.region     |   AWS region to use. | us-east-1
| spring.ai.bedrock.aws.access-key | AWS access key.  | -
| spring.ai.bedrock.aws.secret-key | AWS secret key.  | -
|====


The prefix `spring.ai.bedrock.llama2.chat` is the property prefix that configures the `ChatClient` implementation for Llama2.

[cols="8,4,3"]
|====
| Property | Description | Default

| spring.ai.bedrock.llama2.chat.enabled              | Enable or disable support for Llama2  | false
| spring.ai.bedrock.llama2.chat.model                | The model id to use (See Below) | meta.llama2-70b-chat-v1
| spring.ai.bedrock.llama2.chat.temperature          | Controls the randomness of the output. Values can range over [0.0,1.0], inclusive. A value closer to 1.0 will produce responses that are more varied, while a value closer to 0.0 will typically result in less surprising responses from the model. This value specifies default to be used by the backend while making the call to the model. | 0.7
| spring.ai.bedrock.llama2.chat.top-p                | The maximum cumulative probability of tokens to consider when sampling. The model uses combined Top-k and nucleus sampling. Nucleus sampling considers the smallest set of tokens whose probability sum is at least topP. | AWS Bedrock default
| spring.ai.bedrock.llama2.chat.max-gen-len          | Specify the maximum number of tokens to use in the generated response. The model truncates the response once the generated text exceeds maxGenLen. | 300
|====

Look at the Spring AI enumeration, `Llama2ChatModel`  for other model IDs.  The other value supported is `meta.llama2-13b-chat-v1`.

Model ID values can also be found in the https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html[AWS Bedrock documentation for base model IDs].