= Apache Cassandra

This section walks you through setting up `CassandraVectorStore` to store document embeddings and perform similarity searches.

== What is Apache Cassandra ?

link:https://cassandra.apache.org[Apache Cassandra] is a true open source distributed database reknown for scalability and high availability without compromising performance.

Linear scalability and proven fault-tolerance on commodity hardware or cloud infrastructure makes it the perfect platform for mission-critical data.  Its Vector Similarity Search (VSS) is based on the JVector library that offers best-in-class performance and relevancy.

A vector search in Apache Cassandra is done as simply as:
```
SELECT content FROM table ORDER BY content_vector ANN OF query_embedding ;
```

More docs on this can be read https://cassandra.apache.org/doc/latest/cassandra/getting-started/vector-search-quickstart.html[here].

The Spring AI Cassandra Vector Store is designed to work for both brand new RAG applications as well as being able to be retrofitted on top of existing data and tables.  This vector store may also equally be used for non-RAG non_AI use-cases, e.g. semantic searcing in an existing database.  The Vector Store will automatically create, or enhance, the schema as needed according to its configuration.  If you don't want the schema modifications, configure the store with `disallowSchemaCreation`.

== What is JVector Vector Search?

link:https://github.com/jbellis/jvector[JVector] is a pure Java embedded vector search engine.

It stands out from other HNSW Vector Similarity Search implementations by being

* Algorithmic-fast. JVector uses state of the art graph algorithms inspired by DiskANN and related research that offer high recall and low latency.
* Implementation-fast. JVector uses the Panama SIMD API to accelerate index build and queries.
* Memory efficient. JVector compresses vectors using product quantization so they can stay in memory during searches. (As part of our PQ implementation, our SIMD-accelerated kmeans class is 5x faster than the one in Apache Commons Math.)
* Disk-aware. JVector’s disk layout is designed to do the minimum necessary iops at query time.
* Concurrent. Index builds scale linearly to at least 32 threads. Double the threads, half the build time.
* Incremental. Query your index as you build it. No delay between adding a vector and being able to find it in search results.
* Easy to embed. API designed for easy embedding, by people using it in production.

== Prerequisites

1. A `EmbeddingClient` instance to compute the document embeddings. This is usually configured as a Spring Bean.  Several options are available:

- `Transformers Embedding` - computes the embedding in your local environment. The default is via ONNX and the all-MiniLM-L6-v2 Sentence Transformers. This just works.
- If you want to use OpenAI's Embeddings` - uses the OpenAI embedding endpoint. You need to create an account at link:https://platform.openai.com/signup[OpenAI Signup] and generate the api-key token at link:https://platform.openai.com/account/api-keys[API Keys].
- There are many more choices, see `Embeddings API` docs.

2. An Apache Cassandra instance, from version 5.0-beta1
a. link:https://cassandra.apache.org/_/quickstart.html[DIY Quick Start]
b. For a managed offering https://astra.datastax.com/[Astra DB] offers a healthy free tier offering.

== Dependencies

Add these dependencies to your project:

* For just the Cassandra Vector Store

[source,xml]
----
<dependency>
  <groupId>org.springframework.ai</groupId>
  <artifactId>spring-ai-cassandra</artifactId>
</dependency>
----

* Or, for everything you need in a RAG application (using the default ONNX Embedding Client)

[source,xml]
----
<dependency>
  <groupId>org.springframework.ai</groupId>
  <artifactId>spring-ai-cassandra-spring-boot-starter</artifactId>
</dependency>
----


TIP: Refer to the xref:getting-started.adoc#dependency-management[Dependency Management] section to add the Spring AI BOM to your build file.

* If for example you want to use the OpenAI modules, remember to provide your OpenAI API Key. Set it as an environment variable like so:

[source,bash]
----
export SPRING_AI_OPENAI_API_KEY='Your_OpenAI_API_Key'
----


== Usage

Create a CassandraVectorStore instance connected to your Apache Cassandra database:

[source,java]
----
@Bean
public VectorStore vectorStore(EmbeddingClient embeddingClient) {

  CassandraVectorStoreConfig config = CassandraVectorStoreConfig.builder().build();

  return new CassandraVectorStore(config, embeddingClient);
}
----

> [NOTE]
> It is more convenient and preferred to create the `CassandraVectorStore` as a Bean.
> 
> But if you decide you can create it manually.

> [NOTE]
> The default configuration connects to Cassandra at localhost:9042 and will automatically create the default schema at `springframework_ai_vector.springframework_ai_vector_store`.
>
> Please see `CassandraVectorStoreConfig.Builder` for all the configuration options.

> [NOTE]
> The Cassandra Java Driver is easiest configured via the `application.conf` file on the classpath.
>
> More info can be found link: https://github.com/apache/cassandra-java-driver/tree/4.x/manual/core/configuration[here].


Then in your main code, create some documents:

[source,java]
----
List<Document> documents = List.of(
   new Document("Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!!", Map.of("country", "UK", "year", 2020)),
   new Document("The World is Big and Salvation Lurks Around the Corner", Map.of()),
   new Document("You walk forward facing the past and you turn back toward the future.", Map.of("country", "NL", "year", 2023)));
----

Now add the documents to your vector store:


[source,java]
----
vectorStore.add(documents);
----

And finally, retrieve documents similar to a query:

[source,java]
----
List<Document> results = vectorStore.similaritySearch(
   SearchRequest
      .query("Spring")
      .withTopK(5));
----

If all goes well, you should retrieve the document containing the text "Spring AI rocks!!".

=== Metadata filtering

You can leverage the generic, portable link:https://docs.spring.io/spring-ai/reference/api/vectordbs.html#_metadata_filters[metadata filters] with the CassandraVectorStore as well.  Metadata fields must be configured in `CassandraVectorStoreConfig`.

For example, you can use either the text expression language:

[source,java]
----
vectorStore.similaritySearch(
   SearchRequest
      .query("The World")
      .withTopK(TOP_K)
      .withSimilarityThreshold(SIMILARITY_THRESHOLD)
      .withFilterExpression("country in ['UK', 'NL'] && year >= 2020"));
----

or programmatically using the expression DSL:

[source,java]
----
FilterExpressionBuilder b = new FilterExpressionBuilder();

vectorStore.similaritySearch(
   SearchRequest
      .query("The World")
      .withTopK(TOP_K)
      .withSimilarityThreshold(SIMILARITY_THRESHOLD)
      .withFilterExpression(b.and(
         b.in("country", "UK", "NL"),
         b.gte("year", 2020)).build()));
----

The portable filter expressions get automatically converted into link:https://cassandra.apache.org/doc/latest/cassandra/developing/cql/index.html[CQL queries].

Metadata fields to be searchable need to be either primary key columns or SAI indexed.  To do this configure the metadata field with the `SchemaColumnTags.INDEXED`.
