= Chroma

This section will walk you through setting up the Chroma VectorStore to store document embeddings and perform similarity searches.

link:https://github.com/chroma-core/chroma/pkgs/container/chroma[Chroma Container]

== What is Chroma?

link:https://docs.trychroma.com/[Chroma] is the open-source embedding database. It gives you the tools to store document embeddings, content, and metadata and to search through those embeddings, including metadata filtering.

=== Prerequisites

1. OpenAI Account: Create an account at link:https://platform.openai.com/signup[OpenAI Signup] and generate the token at link:https://platform.openai.com/account/api-keys[API Keys].

2. Access to ChromeDB. The <<appendix-a, setup local ChromaDB>> appendix shows how to set up a DB locally with a Docker container.

On startup, the `ChromaVectorStore` creates the required collection if one is not provisioned already.

== Configuration

To set up ChromaVectorStore, you'll need to provide your OpenAI API Key. Set it as an environment variable like so:

[source,bash]
----
export SPRING_AI_OPENAI_API_KEY='Your_OpenAI_API_Key'
----

== Dependencies

Add these dependencies to your project:

* OpenAI: Required for calculating embeddings.

[source,xml]
----
<dependency>
 <groupId>org.springframework.ai</groupId>
 <artifactId>spring-ai-openai-spring-boot-starter</artifactId>
 <version>0.7.0-SNAPSHOT</version>
</dependency>
----

* Chroma VectorStore.

[source,xml]
----
<dependency>
  <groupId>org.springframework.ai</groupId>
  <artifactId>spring-ai-chroma-store</artifactId>
  <version>0.7.0-SNAPSHOT</version>
</dependency>
----

== Sample Code

Create a `RestTemplate` instance with proper ChromaDB authorization configurations and Use it to create a `ChromaApi` instance:

[source,java]
----
@Bean
public RestTemplate restTemplate() {
   return new RestTemplate();
}

@Bean
public ChromaApi chromaApi(RestTemplate restTemplate) {
   String chromaUrl = "http://localhost:8000";
   ChromaApi chromaApi =  ChromaApi(chromaUrl, restTemplate);
   return chromaApi;
}
----

[NOTE]
====
For ChromaDB secured with link:https://docs.trychroma.com/usage-guide#static-api-token-authentication[Static API Token Authentication] use the `ChromaApi#withKeyToken(<Your Token Credentials>)` method to set your credentials. Check the `ChromaWhereIT` for an example.

For ChromaDB secured with link:https://docs.trychroma.com/usage-guide#basic-authentication[Basic Authentication] use the `ChromaApi#withBasicAuth(<your user>, <your password>)` method to set your credentials. Check the `BasicAuthChromaWhereIT` for an example.
====

Integrate with OpenAI's embeddings by adding the Spring Boot OpenAI starter to your project. This provides you with an implementation of the Embeddings client:

[source,java]
----
@Bean
public VectorStore chromaVectorStore(EmbeddingClient embeddingClient, ChromaApi chromaApi) {
 return new ChromaVectorStore(embeddingClient, chromaApi, "TestCollection");
}
----

In your main code, create some documents:

[source,java]
----
List<Document> documents = List.of(
 new Document("Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!!", Map.of("meta1", "meta1")),
 new Document("The World is Big and Salvation Lurks Around the Corner"),
 new Document("You walk forward facing the past and you turn back toward the future.", Map.of("meta2", "meta2")));
----

Add the documents to your vector store:

[source,java]
----
vectorStore.add(List.of(document));
----

And finally, retrieve documents similar to a query:

[source,java]
----
List<Document> results = vectorStore.similaritySearch("Spring", 5);
----

If all goes well, you should retrieve the document containing the text "Spring AI rocks!!".

=== Metadata filtering

You can leverage the generic, portable link:https://docs.spring.io/spring-ai/reference/api/vectordbs.html#_metadata_filters[metadata filters] with ChromaVector store as well.

For example, you can use either the text expression language:

[source,java]
----
vectorStore.similaritySearch("The World", TOP_K, SIMILARITY_THRESHOLD,
      "author in ['john', 'jill'] && article_type == 'blog'");
----

or programmatically using the `Filter.Expression` DSL:

[source,java]
----
FilterExpressionBuilder b = new FilterExpressionBuilder();

vectorStore.similaritySearch("The World", TOP_K, SIMILARITY_THRESHOLD,
	b.and(
		b.in(List.of("john", "jill")),
		b.eq("article_type", "blog")).build());
----

NOTE: Those (portable) filter expressions get automatically converted into the proprietary Chroma `where` link:https://docs.trychroma.com/usage-guide#using-where-filters[filter expressions].

For example, this portable filter expression:

```sql
author in ['john', 'jill'] && article_type == 'blog'
```

is converted into the proprietary Chroma format

```json
{"$and":[
	{"author": {"$in": ["john", "jill"]}},
	{"article_type":{"$eq":"blog"}}]
}
```

=== Run Chroma Locally

```shell
docker run -it --rm --name chroma -p 8000:8000 ghcr.io/chroma-core/chroma:0.4.15
```

Starts a chroma store at <http://localhost:8000/api/v1>

