= Elasticsearch

This section walks you through setting up the Elasticsearch `VectorStore` to store document embeddings and perform similarity searches.

link:https://www.elastic.co/elasticsearch[Elasticsearch] is an open source search and analytics engine based on the Apache Lucene library.

== Prerequisites

First you need access to an Elasticsearch instance.

On startup, the `ElasticsearchVectorStore` will attempt to create the index mapping.

Optionally, you can do this manually like so:

[source,text]
----
PUT spring-ai-document-index
{
    "mappings": {
        "properties": {
            "embedding": {
                "type": "dense_vector",
                "dims": 1536,
                "index": true,
                "similarity": cosine
            }
        }
    }
}
----

TIP: replace the `1536` with the actual embedding dimension if you are using a different dimension.

Next if required, an API key for the xref:api/embeddings.adoc#available-implementations[EmbeddingClient] to generate the embeddings stored by the `ElasticsearchVectorStore`.

== Dependencies

Add the ElasticsearchVectorStore boot starter dependency to your project:

[source,xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-elasticsearch-store-spring-boot-starter</artifactId>
</dependency>
----

or to your Gradle `build.gradle` build file.

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-elasticsearch-store-spring-boot-starter'
}
----

The Vector Store, also requires an `EmbeddingClient` instance to calculate embeddings for the documents.
You can pick one of the available xref:api/embeddings.adoc#available-implementations[EmbeddingClient Implementations].

For example to use the xref:api/embeddings/openai-embeddings.adoc[OpenAI EmbeddingClient] add the following dependency to your project:

[source,xml]
----
<dependency>
	<groupId>org.springframework.ai</groupId>
	<artifactId>spring-ai-openai-spring-boot-starter</artifactId>
</dependency>
----

or to your Gradle `build.gradle` build file.

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-openai-spring-boot-starter'
}
----

TIP: Refer to the xref:getting-started.adoc#dependency-management[Dependency Management] section to add the Spring AI BOM to your build file.
Refer to the xref:getting-started.adoc#repositories[Repositories] section to add Milestone and/or Snapshot Repositories to your build file.

To connect to Elasticsearch, create a `RestClient` bean and provide the access details for your instance.

[source,java]
----
@Bean
public RestClient restClient() {
    return RestClient.builder(HttpHost.create("http://localhost:9200"))
            .build();
}
----

Next, you can provide the `ElasticsearchVectorStore` configuration via Spring Boot's `application.yml`:

[source,yaml]
----
spring:
  ai:
    vectorstore:
      elasticsearch:
        index-name: spring-ai-index
----

TIP: Check the list of <<elasticsearchvector-properties, configuration parameters>> to learn about the default values and configuration options.

In your main code, create some documents:

[source,java]
----
List<Document> documents = List.of(
	new Document("Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!!", Map.of("meta1", "meta1")),
	new Document("The World is Big and Salvation Lurks Around the Corner"),
	new Document("You walk forward facing the past and you turn back toward the future.", Map.of("meta2", "meta2")));
----

Add the documents to Elasticsearch:

[source,java]
----
vectorStore.add(List.of(document));
----

And finally, retrieve documents similar to a query:

[source,java]
----
List<Document> results = vectorStore.similaritySearch(SearchRequest.query("Spring").withTopK(5));
----

If all goes well, you should retrieve the document containing the text "Spring AI rocks!!".

[[elasticsearchvector-properties]]
== ElasticsearchVectorStore Properties

You can use the following properties in your Spring Boot configuration to customize the Elasticsearch Vector Store.


|===
|Property |Default Value

|`spring.ai.vectorstore.elasticsearch.index-name`
|spring-ai-document-index
|===

