CREATE TABLE SPRING_AI_CHAT_MEMORY (
    CONVERSATION_ID VARCHAR2(36 CHAR) NOT NULL,
    CONTENT CLOB NOT NULL,
    "TYPE" VARCHAR2(10 CHAR) NOT NULL CHECK ("TYPE" IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')),
    "TIMESTAMP" TIMESTAMP NOT NULL
);

CREATE INDEX SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_TIMESTAMP_IDX ON SPRING_AI_CHAT_MEMORY(CONVERSATION_ID, "TIMESTAMP");
