IF OBJECT_ID('SPRING_AI_CHAT_MEMORY', 'U') IS NULL
CREATE TABLE SPRING_AI_CHAT_MEMORY (
    conversation_id VARCHAR(36) NOT NULL,
    content NVARCHAR(MAX) NOT NULL,
    type VARCHAR(10) NOT NULL,
    [timestamp] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT TYPE_CHECK CHECK (type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'))
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_TIMESTAMP_IDX')
CREATE INDEX SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_TIMESTAMP_IDX ON SPRING_AI_CHAT_MEMORY(conversation_id, [timestamp] DESC);
