/*
 * Copyright 2023-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.ai.anthropic;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import com.anthropic.client.AnthropicClient;
import com.anthropic.core.http.HttpResponse;
import com.anthropic.models.beta.files.FileMetadata;
import com.anthropic.models.messages.BashCodeExecutionOutputBlock;
import com.anthropic.models.messages.BashCodeExecutionToolResultBlock;
import com.anthropic.models.messages.CodeExecutionOutputBlock;
import com.anthropic.models.messages.CodeExecutionToolResultBlock;
import com.anthropic.models.messages.CodeExecutionToolResultBlockContent;
import com.anthropic.models.messages.ContentBlock;
import com.anthropic.models.messages.Message;
import org.jspecify.annotations.Nullable;

import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.util.Assert;

/**
 * Helper utilities for working with Anthropic Claude Skills responses and files. Provides
 * methods to extract file IDs, container IDs, and download files generated by Skills.
 *
 * <p>
 * Unlike the RestClient module's helper which requires recursive Map/List crawling to
 * find file IDs in untyped response structures, this SDK-based helper uses the SDK's
 * typed {@link ContentBlock} variants with direct accessor methods.
 *
 * @author Soby Chacko
 * @since 2.0.0
 */
public final class AnthropicSkillsResponseHelper {

	private AnthropicSkillsResponseHelper() {
	}

	/**
	 * Extract all file IDs from a chat response. Searches through all content blocks in
	 * the underlying SDK {@link Message} stored in response metadata.
	 * @param response the chat response to search
	 * @return list of file IDs found in the response (empty list if none found)
	 */
	public static List<String> extractFileIds(@Nullable ChatResponse response) {
		if (response == null) {
			return List.of();
		}

		Message message = getMessageFromMetadata(response);
		if (message == null) {
			return List.of();
		}

		List<String> fileIds = new ArrayList<>();
		for (ContentBlock block : message.content()) {
			if (block.isContainerUpload()) {
				fileIds.add(block.asContainerUpload().fileId());
			}
			else if (block.isBashCodeExecutionToolResult()) {
				extractFileIdsFromBashResult(block.asBashCodeExecutionToolResult(), fileIds);
			}
			else if (block.isCodeExecutionToolResult()) {
				extractFileIdsFromCodeExecutionResult(block.asCodeExecutionToolResult(), fileIds);
			}
		}
		return fileIds;
	}

	/**
	 * Extract container ID from a chat response for multi-turn conversation reuse.
	 * @param response the chat response
	 * @return container ID if present, null otherwise
	 */
	public static @Nullable String extractContainerId(@Nullable ChatResponse response) {
		if (response == null) {
			return null;
		}

		Message message = getMessageFromMetadata(response);
		if (message == null) {
			return null;
		}

		return message.container().map(container -> container.id()).orElse(null);
	}

	/**
	 * Download all files from a Skills response to a target directory.
	 * @param response the chat response containing file IDs
	 * @param client the Anthropic client to use for downloading (beta files API)
	 * @param targetDir directory to save files (must exist)
	 * @return list of paths to saved files
	 * @throws IOException if file download or saving fails
	 */
	public static List<Path> downloadAllFiles(ChatResponse response, AnthropicClient client, Path targetDir)
			throws IOException {
		Assert.notNull(response, "Response cannot be null");
		Assert.notNull(client, "AnthropicClient cannot be null");
		Assert.notNull(targetDir, "Target directory cannot be null");
		Assert.isTrue(Files.isDirectory(targetDir), "Target path must be a directory");

		List<String> fileIds = extractFileIds(response);
		List<Path> savedPaths = new ArrayList<>();

		for (String fileId : fileIds) {
			FileMetadata metadata = client.beta().files().retrieveMetadata(fileId);
			try (HttpResponse httpResponse = client.beta().files().download(fileId)) {
				byte[] content = httpResponse.body().readAllBytes();
				Path filePath = targetDir.resolve(metadata.filename());
				Files.write(filePath, content);
				savedPaths.add(filePath);
			}
		}

		return savedPaths;
	}

	private static void extractFileIdsFromBashResult(BashCodeExecutionToolResultBlock resultBlock,
			List<String> fileIds) {
		BashCodeExecutionToolResultBlock.Content content = resultBlock.content();
		if (content.isBashCodeExecutionResultBlock()) {
			for (BashCodeExecutionOutputBlock outputBlock : content.asBashCodeExecutionResultBlock().content()) {
				fileIds.add(outputBlock.fileId());
			}
		}
	}

	private static void extractFileIdsFromCodeExecutionResult(CodeExecutionToolResultBlock resultBlock,
			List<String> fileIds) {
		CodeExecutionToolResultBlockContent content = resultBlock.content();
		if (content.isResultBlock()) {
			for (CodeExecutionOutputBlock outputBlock : content.asResultBlock().content()) {
				fileIds.add(outputBlock.fileId());
			}
		}
	}

	private static @Nullable Message getMessageFromMetadata(ChatResponse response) {
		if (response.getMetadata() == null) {
			return null;
		}
		Object anthropicResponse = response.getMetadata().get("anthropic-response");
		if (anthropicResponse instanceof Message message) {
			return message;
		}
		return null;
	}

}
