[[ChatClient]]
= ChatClient

The `ChatClient` interface streamlines interactions with xref:concepts.adoc#_models[AI Models].
It simplifies connecting to various AI Models -— each with potentially unique APIs -— by offering a uniform interface for interaction.

Currently, the interface supports only text-based input and output.
You should expect some of the classes and interfaces to change as we add other input and output types.

The design of the `ChatClient` interface centers around two primary goals:

* *Portability*: It allows easy integration with different AI Models, letting developers switch between differing AI models with minimal code changes.
This design aligns with Spring's philosophy of modularity and interchangeability.

* *Simplicity*: By using companion classes like `Prompt` for input encapsulation and `AiResponse` for output handling, the `ChatClient` interface simplifies communication with AI Models. It manages the complexity of request preparation and response parsing, offering a direct and simplified API interaction.

== API Overview

This section provides a guide to the `ChatClient` interface and associated classes.

=== ChatClient
Here is the `ChatClient` interface definition:

```java
public interface ChatClient {

    default String generate(String message) { // implementation omitted
    }

    AiResponse generate(Prompt prompt);

}
```

The `generate` method with a `String` parameter simplifies initial use, avoiding the complexities of the more sophisticated `Prompt` and `AiResponse` classes.

=== Prompt
In a real-world application, it is most common to use the `generate` method, taking a `Prompt` instance and returning an `AiResponse`.

The `Prompt` class encapsulates a list of `Message` objects.
The following listing shows a truncated version of the Prompt class, excluding constructors and other utility methods:

```java
public class Prompt {

    private final List<Message> messages;

    // constructors and utility methods omitted
}
```

=== Message

The `Message` interface encapsulates a textual message, a collection of attributes as a `Map`, and a categorization known as `MessageType`. The interface is defined as follows:

```java
public interface Message {

   String getContent();

   Map<String, Object> getProperties();

   MessageType getMessageType();

}
```

The `Message` interface has various implementations that correspond to the categories of messages that an AI model can process.
Some models, like OpenAI's chat completion endpoint, distinguish between message categories based on conversational roles, effectively mapped by the `MessageType`.

For instance, OpenAI recognizes message categories for distinct conversational roles such as "`system,`" "`user,`" or "`assistant.`"
While the term, `MessageType`, might imply a specific message format, in this context, it effectively designates the role a message plays in the dialogue.

For AI models that do not use specific roles, the `UserMessage` implementation acts as a standard category, typically representing user-generated inquiries or instructions.
To understand the practical application and the relationship between `Prompt` and `Message`, especially in the context of these roles or message categories, see the detailed explanations in the xref:api/prompt.adoc[Prompts] section.

=== AiResponse

The structure of the `AiResponse` class is as follows:

```java
public class AiResponse {

	private final List<Generation> generations;

    // other methods omitted
}
```

The `AiResponse` class holds the AI Model's output, with each `Generation` instance containing one of potentially multiple outputs from a single prompt.

The `AiResponse` class also carries a map of key-value pairs providing metadata about the AI Model's response. This feature is still in progress and is not elaborated on in this document.

=== Generation

Finally, the `Generation` class contains a `String` that represents the output text and a map that provides metadata about this response:


```java
public class Generation {

	private final String text;

	private Map<String, Object> info;

}
```

== Available Implementations

The `ChatClient` interface has the following available implementations:

* OpenAI: Using the https://github.com/TheoKanning/openai-java[Theo Kanning client library].
* Azure OpenAI: Using https://learn.microsoft.com/en-us/java/api/overview/azure/ai-openai-readme?view=azure-java-preview[Microsoft's OpenAI client library].
* Hugging Face: Using the https://huggingface.co/inference-endpoints[Hugging Face Hosted Inference Service].  This gives you access to hundreds of models.
* https://ollama.ai/[Ollama]: Run large language models locally.

Planned implementations

* Amazon Bedrock: This can provide access to many AI models.
* Google Vertex: Providing access to 'Bard' (AKA Palm2).

Others are welcome. The list is not at all closed.

== OpenAI-Compatible Models

A variety of models compatible with the OpenAI API are available, including those that can be operated locally, such as https://github.com/mudler/LocalAI[LocalAI]. The standard configuration for connecting to the OpenAI API is through the `spring.ai.openai.baseUrl` property, which defaults to `https://api.openai.com`.

To link the OpenAI client to a compatible model that uses the OpenAI API, you should adjust the `spring.ai.openai.baseUrl` property to the corresponding URL of the model you wish to connect to.

== Configuration

This section describes how to configure models, including:

* <<openai-api,OpenAI>>
* <<azure-openai-api,Azure OpenAI>>
* <<hugging-face-api,Hugging Face>>
* <<ollama-api,Ollama>>

[[openan-api]]
=== OpenAI

Add the Spring Boot starter to you project's dependencies:

[source, xml]
----
    <dependency>
        <groupId>org.springframework.ai</groupId>
        <artifactId>spring-ai-azure-openai-spring-boot-starter</artifactId>
        <version>0.8.0-SNAPSHOT</version>
    </dependency>
----

This makes an instance of the `ChatClient` that is backed by the https://github.com/TheoKanning/openai-java[Theo Kanning client library] available for injection in your application classes.

The Spring AI project defines a configuration property named `spring.ai.openai.api-key` that you should set to the value of the `API Key` obtained from `openai.com`.

Exporting an environment variable is one way to set that configuration property.

[source,shell]
----
export SPRING_AI_OPENAI_API_KEY=<INSERT KEY HERE>
----

[[azure-openai-api]]
=== Azure OpenAI

This makes an instance of the `ChatClient` that is backed by https://learn.microsoft.com/en-us/java/api/overview/azure/ai-openai-readme?view=azure-java-preview[Microsoft's OpenAI client library] available for injection in your application classes.

The Spring AI project defines a configuration property named `spring.ai.azure.openai.api-key` that you should set to the value of the `API Key` obtained from Azure.
There is also a configuration property named `spring.ai.azure.openai.endpoint` that you should set to the endpoint URL obtained when provisioning your model in Azure.

Exporting environment variables is one way to set these configuration properties.

[source,shell]
----
export SPRING_AI_AZURE_OPENAI_API_KEY=<INSERT KEY HERE>
export SPRING_AI_AZURE_OPENAI_ENDPOINT=<INSERT ENDPOINT URL HERE>
----

[[hugging-face-api]]
=== Hugging Face

There is not yet a Spring Boot Starter for this client implementation, so you should add the dependency to the HuggingFace client implementation to your project's dependencies and export an environment variable:

[source, xml]
----
<dependency>
  <groupId>org.springframework.ai</groupId>
  <artifactId>spring-ai-huggingface</artifactId>
  <version>0.8.0-SNAPSHOT</version>
</dependency>
----

[source,shell]
----
export HUGGINGFACE_API_KEY=your_api_key_here
----

Obtain the endpoint URL of the inference endpoint. You can find this on the Inference Endpoint's UI https://ui.endpoints.huggingface.co/[here].

[[ollama-api]]
=== Ollama

There is not yet a Spring Boot Starter for this client implementation, so you should add the dependency to the Ollama client implementation to your project's dependencies:

[source, xml]
----
<dependency>
  <groupId>org.springframework.ai</groupId>
  <artifactId>spring-ai-ollama</artifactId>
  <version>0.8.0-SNAPSHOT</version>
</dependency>
----

== Example Usage

The following listing shows a simple "Hello, world" example. It uses the `ChatClient.generate` method that takes a `String` as input and returns a `String` as output:

[source,java]
----
@RestController
public class SimpleAiController {

    private final ChatClient chatClient;

    @Autowired
    public SimpleAiController(ChatClient chatClient) {
        this.chatClient = chatClient;
    }

    @GetMapping("/ai/generate")
    public Map generate(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        return Map.of("generation", chatClient.generate(message));
    }
}
----

== Best Practices

TBD

== Troubleshooting

TBD

== API Docs

You can find the Javadoc https://docs.spring.io/spring-ai/docs/current-SNAPSHOT/[here].

== Feedback and Contributions

The project's https://github.com/spring-projects/spring-ai/discussions[GitHub discussions] is a great place to send feedback.

== Related Resources

TBD
