= Design Document 02 - Spring Boot Modularity

This document explains the rationale behind module boundary choices,
the use and dependency of Spring AI on Spring Boot and how the build
infrastructure is configured to enforce these architectural decisions to
the best extent.

== Problems
The Spring AI core classes should be usable without Spring Boot and as
such should not depend on boot. Core classes include common modules,
various `model` implementations (be it `ChatModel`, `ImageModel`, _etc._ ),
`VectorStore` abstraction and implementations, but also the `ChatClient`
abstraction and `Advisors`, MCP support. As a matter of fact, all
functionality of Spring AI is available to a plain Spring Framework app.

That being said, Spring AI also provides boot users with dedicated support
in the form of `auto-configuration` modules that help wire a Spring AI
app quickly. Such modules obviously do depend on Spring Boot. In accordance
with best practices exposed https://docs.spring.io/spring-boot/reference/features/developing-auto-configuration.html[here], these modules should have zero impact if the underlying
libraries are not present on the application classpath. As a consequence,
all dependencies of those `auto-configuration` modules which are not
dedicated to tests should be marked `optional` (including the `spring-boot-autoconfigure` module which triggers the `@AutoConfiguration` classes. It is thus the responsibility of end users
to add `spring-boot-autoconfigure` if they depend on `auto-configuration` modules alone, or use a starter, see below).

Lastly, `starters` provide end users with an opinionated way to
quickly bootstrap an application with everything needed to leverage
some feature X. As a consequence, those modules (which do not contain code)
are responsible for dragging the autoconfiguration module for X, but also
the transitive dependencies that this module requires. Such starters can
themselves depend on other starters when this makes sense. They also make
`auto-configuration` modules do their magic by virtue of bringing `spring-boot-autoconfigure` (via `spring-boot-starter`)

== Solution
Starting with Spring AI 2.0, the code base has been revisited to enforce
these principles. In particular, the `maven-enforcer-plugin` and its
`bannedDependencies` rule have been configured to make sure that

* the core codebase does NOT depend on boot,
* all dependencies of `auto-configurations` have been marked `optional=true`

=== User Impact
There should be no end user impact for those that consume Spring AI via starters. For users that rely on `auto-configurations` directly, given
that some inconsistencies have been fixed here and there, this may require
adding back a dependency that was incorrectly provided in the past.
