package org.springframework.ai.dashscope.record.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A chat completion message generated by the model.
 *
 * @param message
 * @author Nottyjay Ji
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ChatCompletionChoice(@JsonProperty("finish_reason") String finishReason,
		@JsonProperty("message") ChatCompletionMessage message) {
}
