package org.springframework.ai.dashscope.record.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Message comprising the conversation.
 *
 * @param content The contents of the message.
 * @param role The role of the messages author. Could be one of the {@link Role} types.
 * @param name An optional name for the participant. Provides the model information to
 * differentiate between participants of the same role. In case of Function calling, the
 * name is the function name that the message is responding to.
 * @param toolCalls The tool calls generated by the model, such as function calls.
 * Applicable only for {@link Role#ASSISTANT} role and null otherwise.
 * @author Nottyjay Ji
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ChatCompletionMessage(@JsonProperty("role") Role role, @JsonProperty("content") String content,
		@JsonProperty("name") String name, @JsonProperty("tool_calls") List<ToolCall> toolCalls) {

	public ChatCompletionMessage(Role role, String content) {
		this(role, content, null, null);
	}

	/** The role of the author of this message. */
	public enum Role {

		/** System message. */
		@JsonProperty("system")
		SYSTEM,
		/** User message. */
		@JsonProperty("user")
		USER,
		/** Assistant message. */
		@JsonProperty("assistant")
		ASSISTANT,
		/** Tool message. */
		@JsonProperty("tool")
		TOOL

	}
}
