name: Build Release
runs:
  using: composite
  steps:
    - name: Build Release
      shell: bash
      run: ./mvnw --batch-mode -ntp -PreleaseTrain --settings release-train-settings.xml -DaltDeploymentRepository="release-train::file://$(pwd)/deployment-repository" -Dmaven.test.skip deploy
